package com.day3.taskexceptions;

public class division {
	public static void main(String[]args) {
		Scanner sc=new Scanner(System.in);
		int a =sc.nextInt();
		int b =sc.nextInt();
		int c;
		try {
			c=b/a;
			
		}catch(ArithmeticException e) {
			System.out.println("DivideByZeroException");
		}finally {
			System.out.println(a+" "+b+""+c);
			System.out.println("Inside Finnaly Block");
		}
	}
}
